openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0
servers:
  - url: 'http://dret.net/weather'
paths:
  /forecast:
    get:
      summary: Get the weather forecast.
      responses:
        '200':
          description: Successful operation.
        '400':
          description: Invalid request.
        '500':
          description: Server error.